language: cpp
env:
  global:
  - QTC_VERSION="4.12"
  - PLUGIN_VERSION="0.4.9";
git:
  depth: 1
root: required
dist: bionic
install:
- bash ci-scripts/$TRAVIS_OS_NAME/install.sh
script:
- bash ci-scripts/$TRAVIS_OS_NAME/build.sh
jobs:
  include:
  - os: osx
    osx_image: xcode10.1
  - os: linux
    compiler: gcc
before_deploy:
  - git config --local user.name "Francesc Martinez"
  - git config --local user.email "francescmm@gmail.com"
  - export FILE=$(ls libDoxygen_${PLUGIN_VERSION}-qtc${QTC_VERSION}.*)
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: 'true'
  draft: true
  file: "${FILE}"
  api_key:
    secure: xNpWbImodwaDPTsIROYOzAM+BIFs/Tlw+hWBk8aAFF9LfH2FVpxJAkYbAwhhoh4774j6n96cRirjfsOfSKKK9g2jpuvgPeVfY8UHeXB3KmZs3WsMHp1kmDrwk6Y46X7yfOb50VUFSTvPQn7PSZzc6vJtM5BxXHhaSGPcKZjKm68GQup6jDbzbS53vSYCMCOJLSXdcfZrM5Ot7C25JTbtXj02nPSZoloBV6XuSy01/Mt4Z1f6a1CN+fyX/0p+kf8/FgbGIsfuBkzZpxzhSbn+a2/SNL2qR5UwoOLQLKpAbVVFFi/uiRcmbMs50hxuanVmtVp8XOYm+txSc5Bz+iOFufmh4JbuNblMA62+cG8vGREXkcoNXAKpJ9q9VMbJJ94nvlZwiT7MbPPHydB96bY53tZZv14MPgcPqa6Fd+s/wxkCZjW5Ttn04Ltfu+MusLbPUyO1CSyaNJqk1qyV2mOQCHMRhoqXpDSTp24b+7pf38khgt37NGvFNd/1lQOSBntn5Nzrf65xjJzRvLw8TzEZT7Iv5Vt0lKKco1TMAzFfFKTDvu2PeoX0gCw9KHx1Khw64LPqzyFypIPZgRc5vJnKI07pEeb6bcZnzRKXH/IVFyiajf/GOPRDu16PksEesHQ6Qg9h7jsmpQuA0vCIJwKxJa18kr12J4tkLB459rMoeQ0=
  on:
    tags: true
    repo: francescmm/qtcreator-doxygen
